### CREATE five documents.
POST http://localhost:3000/projects HTTP/1.1
content-type: application/json

{
    "projectName": "OSU X Purs Mobile Payment",
    "projectNumber": 1,
    "date": "02-01-2024",
    "link": "https://github.com/muhammadAkbar7/Locale"
}


### CREATE 2
POST http://localhost:3000/projects HTTP/1.1
content-type: application/json

{
    "projectName": "Traffic Congestion Predictor",
    "projectNumber": 2,
    "date": "05-01-2022",
    "link": "https://github.com/muhammadAkbar7/-Traffic-Congestion-Predictor"
}

### CREATE 3
POST http://localhost:3000/projects HTTP/1.1
content-type: application/json

{
    "projectName": "UW Bothell AI Hackathon",
    "projectNumber": 3,
    "date": "04-01-2024",
    "link": "https://devpost.com/software/splash-scholars"
}

### CREATE 4
POST http://localhost:3000/projects HTTP/1.1
content-type: application/json

{
    "projectName": "Personal Website",
    "projectNumber": 4,
    "date": "04-15-2024",
    "link": "https://github.com/muhammadAkbar7/my-personal-website"
}

### CREATE 5
POST http://localhost:3000/projects HTTP/1.1
content-type: application/json

{
    "projectName": "Trivia App",
    "projectNumber": 5,
    "date": "02-15-2024",
    "link": "https://github.com/muhammadAkbar7/IOS-Trivia-Full"
}


### RETRIEVE all documents.
GET http://localhost:3000/projects HTTP/1.1



### RETRIEVE a document by its ID.
### Replace the following ID with one that exists in the collection.
GET http://localhost:3000/projects/665423adbcd517463d2856d6 HTTP/1.1


### UPDATE one document's date, by ID.
### Replace the ID in the following request with one that exists
### and update the date:
PUT http://localhost:3000/projects/665423adbcd517463d2856d6 HTTP/1.1
content-type: application/json

{
    "projectName": "OSU X Purs Mobile Payment",
    "projectNumber": 1,
    "date": "02-17-2024",
    "link": "https://github.com/muhammadAkbar7/Locale"
}

### DELETE by ID (responds with nothing if successful):
DELETE http://localhost:3000/projects/665423f2bcd517463d2856d8 HTTP/1.1



### RETRIEVE all documents (responds with 4 or the original 5):
GET http://localhost:3000/projects HTTP/1.1

